spring.application.name=com
spring.graphql.path=/graphql
spring.datasource.url=jdbc:postgresql://tcp.cloudpub.ru:15432/postgres
spring.datasource.username=postgres
spring.datasource.password=Werest13
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.serialization.fail-on-self-references=false

server.port=8080

spring.jpa.hibernate.ddl-auto=validate
server.address=0.0.0.0

server.compression.enabled=true

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

spring.jpa.properties.hibernate.cache.use_query_cache=true
spring.jpa.properties.hibernate.cache.use_second_level_cache=true

server.compression.mime-types=application/json,application/graphql-response+json,text/javascript,text/css,text/html,text/plain
server.compression.min-response-size=1024
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=kanbandocky.verify@gmail.com
spring.mail.password=zgoa fcjd qexv xpgn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.starttls.enable=false

app.frontend.url=https://kanbandocky.ru
turnstile.secret.key=0x4AAAAAADSqCK4fo_Vi0fo4n4q8APEYkRs

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.engine.transaction.internal.TransactionImpl=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG

app.verification.ttl.hours=24
app.verification.auto-delete.enabled=true
app.verification.cleanup.interval=21600000

logging.level.org.springframework.cache=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=c8e2f9a1d4b7e3f6a9c2d5e8f1b4c7a0d3e6f9b2c5a8d1e4f7b0c3e6f9a2d5b8
jwt.expiration=86400000